# Generated by Django 4.2.1 on 2023-06-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_posts_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='user',
        ),
    ]
