# Generated by Django 4.2.1 on 2023-06-07 12:03

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_posts_user_sharedpost_posts_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='spid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, null=True, prefix='spost', unique=True),
        ),
    ]
