# Generated by Django 4.2.1 on 2023-06-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sharedpost_spid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='original_post_id',
            field=models.IntegerField(null=True),
        ),
    ]
