# Generated by Django 4.2.1 on 2023-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='photos',
        ),
        migrations.AddField(
            model_name='story',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
