# Generated by Django 4.2.1 on 2023-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_story_photos_story_images_story_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='videos',
        ),
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
