# Generated by Django 4.2.1 on 2023-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_story_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
