# Generated by Django 4.2.1 on 2023-06-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_story_images_alter_story_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='videos',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='story',
            name='images',
        ),
    ]
