# Generated by Django 4.2.1 on 2023-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_videos_story_file_remove_story_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
