# Generated by Django 4.2.1 on 2023-06-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_story_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sid',
        ),
    ]
