# Generated by Django 4.2.1 on 2023-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_story_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('profile_pic', models.ImageField(upload_to='pages/profile_pictures/')),
                ('cover_pic', models.ImageField(upload_to='pages/cover_pictures/')),
                ('about', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
