# Generated by Django 4.2.1 on 2023-06-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_page_owner_page_user_posts_page_alter_posts_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sharedpost'),
        ),
    ]
