# Generated by Django 4.2.1 on 2023-06-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_user_created_at'),
        ('core', '0036_alter_posts_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='userauths.profile'),
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
