# Generated by Django 4.2.1 on 2023-06-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_user_created_at'),
        ('core', '0037_page_liked_by_page_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.page'),
        ),
        migrations.AlterField(
            model_name='sharedpost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.profile'),
        ),
    ]
