# Generated by Django 4.2.1 on 2023-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friends',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
