# Generated by Django 4.2.1 on 2023-06-10 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '0008_user_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, null=True, prefix='msg', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reciever_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_profile', to='userauths.profile')),
                ('reciever_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_user', to=settings.AUTH_USER_MODEL)),
                ('sender_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile', to='userauths.profile')),
                ('sender_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
