# Generated by Django 4.2.1 on 2023-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(null=True, upload_to='messages_images/'),
        ),
    ]
