# Generated by Django 4.2.1 on 2023-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_message_body_alter_message_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='reciever_body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='photo',
            new_name='reciever_photo',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_photo',
            field=models.ImageField(blank=True, null=True, upload_to='messages_images/'),
        ),
    ]
