# Generated by Django 4.2.1 on 2023-06-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_rename_body_message_reciever_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciever_photo',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_photo',
        ),
    ]
